---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  information:
    name: ‚ÑπÔ∏è Addon Information
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.information.outputs.name }}
      description: ${{ steps.information.outputs.description }}
      target: ${{ steps.information.outputs.target }}
      build: ${{ steps.information.outputs.build }}
      config: ${{ steps.information.outputs.config }}
      architectures: ${{ steps.information.outputs.architectures }}
      version: ${{ steps.get_next_version.outputs.version }}
      environment: latest
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ‚ÑπÔ∏è Gather Information
        id: information
        uses: frenck/action-addon-information@v1.4.2
      - name: üè∑ Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
        with:
          prefix: ""

  lint:
    name: ‚úèÔ∏è Lint
    runs-on: ubuntu-latest
    needs: [ information ]
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@v4
      - name: ‚úèÔ∏è Addon Lint
        uses: frenck/action-addon-linter@v2.15.1
        with:
          path: "./${{ needs.information.outputs.target }}"
      - name: ‚úèÔ∏è Hadolint
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: "./${{ needs.information.outputs.target }}/Dockerfile"
      - name: ‚úèÔ∏è JSON Lint
        run: |
          shopt -s globstar
          cat **/*.json | jq '.'
      - name: ‚úèÔ∏è Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -s bash
      - name: ‚úèÔ∏è YAMLLint
        uses: frenck/action-yamllint@v1.5
        with:
          config: .yamllint.yaml

  patch:
    name: ‚úèÔ∏è Patch version
    runs-on: ubuntu-latest
    needs: [ information, lint ]
    permissions:
      contents: write
    outputs:
      release_ref: ${{ steps.patch_version.outputs.release_ref }}
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@v4
      - name: üèó Set up git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: ‚úèÔ∏è Patch version
        id: patch_version
        run: |
          yq -iP '.version = "${{needs.information.outputs.version}}"' "${{needs.information.outputs.config}}" -o yaml
          git commit -am "chore(release): version ${{ needs.information.outputs.version }}"
          git push
          echo "release_ref=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  build:
    name: üöÄ Build and Release
    runs-on: ubuntu-latest
    needs: [ information, lint, patch ]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.patch.outputs.release_ref }}
      - name: üèó Set up build cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.docker-cache
          key: docker-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            docker-${{ matrix.architecture }}
      - name: üèó Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: üèó Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: üèó  Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ‚ÑπÔ∏è Compose build flags
        id: flags
        run: |
          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"
          from=$(yq --no-colors eval ".build_from.${{ matrix.architecture }}" "${{ needs.information.outputs.build }}")
          echo "from=${from}" >> "$GITHUB_OUTPUT"

          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
            echo "platform=linux/amd64" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
            echo "platform=linux/386" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
            echo "platform=linux/arm/v6" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
            echo "platform=linux/arm/v7" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
            echo "platform=linux/arm64/v8" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
            exit 1
          fi
      - name: ‚§µÔ∏è Download base image
        if: steps.flags.outputs.from != 'null'
        run: docker pull "${{ steps.flags.outputs.from }}"
      - name: üöÄ Build
        uses: docker/build-push-action@v5.3.0
        with:
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
            ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
          context: ${{ needs.information.outputs.target }}
          file: ${{ needs.information.outputs.target }}/Dockerfile
          cache-from: |
            type=local,src=/tmp/.docker-cache
            ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
          cache-to: type=local,mode=max,dest=/tmp/.docker-cache-new
          platforms: ${{ steps.flags.outputs.platform }}
          build-args: |
            BUILD_ARCH=${{ matrix.architecture }}
            BUILD_DATE=${{ steps.flags.outputs.date }}
            BUILD_DESCRIPTION=${{ needs.information.outputs.description }}
            BUILD_FROM=${{ steps.flags.outputs.from }}
            BUILD_NAME=${{ needs.information.outputs.name }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=${{ needs.information.outputs.version }}
      - name: üöö Swap build cache
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
      - name: üöÄ Push and Release
        run: |
          docker push \
            ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
          docker push \
            ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}

  release:
    name: üöÄ Release
    runs-on: ubuntu-latest
    needs: [ information, lint, patch, build ]
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.patch.outputs.release_ref }}
      - name: üöÄ Create GitHub Release
        run: |
          gh release create v${{ needs.information.outputs.version }} \
          --generate-notes \
          --title "üöÄ v${{ needs.information.outputs.version }}" \
          --target ${{ needs.patch.outputs.release_ref }}
